version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - timge-web
      - timge-backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./timge.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/ssl
    networks:
      - timge-network

  timge-web:
    image: ${DOCKER_IMAGE_WEB}
    container_name: timge-web
    networks:
      - timge-network

  timge-backend:
    image: ${DOCKER_IMAGE_BACKEND}
    container_name: timge-backend
    networks:
      - timge-network

networks:
  timge-network:
    driver: bridge
