version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./timge.conf:/etc/nginx/conf.d/default.conf
    networks:
      - timge-network

  timge-web:
    image: ${DOCKER_IMAGE_WEB}
    networks:
      - timge-network

  timge-backend:
    image: ${DOCKER_IMAGE_BACKEND}
    networks:
      - timge-network

networks:
  timge-network:
    name: timge-network
    driver: bridge
