name: Build and Deploy Timge

on:
  push:
    branches:
      - main
      - fix/23-resolve-webpack-errors

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install OpenVPN
      run: sudo apt-get update && sudo apt-get install -y openvpn

    - name: Configure VPN Authentication
      run: |
        echo -e "${{ secrets.VPN_USER }}\n${{ secrets.VPN_PASS }}" > vpn-auth.txt

    - name: Start OpenVPN
      run: |
        sudo openvpn --config .github/vpn/config.ovpn --auth-user-pass vpn-auth.txt &
        sleep 10
        ping -c 3 ${{ secrets.VM_IP }}
    
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        echo "Current working directory: $(pwd)"
        docker build -t ${{ secrets.DOCKER_IMAGE }}:latest ./web

    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKER_IMAGE }}:latest

    - name: Copy Nginx Configuration
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        source: .github/nginx/timge.conf
        target: /tmp/nginx-config/
    
    - name: Deploy to Cloud VM
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_IMAGE }}:latest

          docker stop timge-web || true
          docker rm timge-web || true

          docker run -d --name timge-web -p 3000:3000 ${{ secrets.DOCKER_IMAGE }}:latest

          # echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt-get update
          # echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt-get install -y nginx certbot python3-certbot-nginx

          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S mv /tmp/nginx-config/timge.conf /etc/nginx/sites-available/timge.conf
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S ln -sf /etc/nginx/sites-available/timge.conf /etc/nginx/sites-enabled/timge.conf

          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S nginx -t || exit 1
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl reload nginx

          # echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S certbot --nginx -n --agree-tos --email "${{ secrets.ADMIN_EMAIL }}" -d "${{ secrets.DOMAIN_NAME }}"

          echo "Deployment complete with HTTPS on port 443"

    - name: Kill VPN Connection
      if: always()
      run: |
        sudo pkill openvpn  