name: VPN Deployment

on:
  push:
    branches:
      - main

jobs:
  vpn-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install OpenVPN
      run: sudo apt-get update && sudo apt-get install -y openvpn

    - name: Configure VPN
      run: echo "${{ secrets.VPN_CONFIG }}" > vpn-config.ovpn

    - name: Connect to VPN
      run: |
        sudo openvpn --config vpn-config.ovpn --daemon &
        echo "Waiting for VPN connection..."
        sleep 15

    - name: Verify VPN connection
      run: ping -c 3 ${{ secrets.VM_IP }}

    - name: Terminate VPN connection
      if: always()
      run: |
        echo "Terminating VPN connection..."
        sudo pkill openvpn
